name: Run Tests on PR

on: pull_request

jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install asdf
        uses: asdf-vm/actions/setup@v1
      - uses: actions/cache@v2
        id: asdf-cache
        with:
          path: |
            /home/runner/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
      - name: Install asdf tools
        run: |
          cat .tool-versions | cut -f 1 -d ' ' | xargs -n 1 asdf plugin-add || true
          asdf plugin-update --all
          asdf install
          asdf reshim
      - name: Install Modules
        run: yarn
      - name: Run lerna bootsrtrap
        run : yarn bootstrap
      - name: Run Lerna link
        run:  yarn llink
      - name: Run Jest Tests
        run : yarn test:jest
